# Generated by Django 4.2.9 on 2024-02-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtoshort',
            old_name='longUrl',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='longtoshort',
            old_name='shortUrl',
            new_name='short_url',
        ),
    ]
